// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt0rH5UhpTlf1Ji2OCC30mKoke58M-q4k',
    appId: '1:639474301712:web:7c334677cad7f40c68c395',
    messagingSenderId: '639474301712',
    projectId: 'otc-recs',
    authDomain: 'otc-recs.firebaseapp.com',
    storageBucket: 'otc-recs.firebasestorage.app',
    measurementId: 'G-91MRJ123HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvNGeI6hGwUrt3HBd5a25oEVssmlD2vCY',
    appId: '1:639474301712:android:533bbe270b7a35f068c395',
    messagingSenderId: '639474301712',
    projectId: 'otc-recs',
    storageBucket: 'otc-recs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Jf5XSuoi2NmHPrCULduMLVEX0xST5DU',
    appId: '1:639474301712:ios:5cd45fdc6f19d06168c395',
    messagingSenderId: '639474301712',
    projectId: 'otc-recs',
    storageBucket: 'otc-recs.firebasestorage.app',
    iosBundleId: 'com.example.otcRecs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Jf5XSuoi2NmHPrCULduMLVEX0xST5DU',
    appId: '1:639474301712:ios:5cd45fdc6f19d06168c395',
    messagingSenderId: '639474301712',
    projectId: 'otc-recs',
    storageBucket: 'otc-recs.firebasestorage.app',
    iosBundleId: 'com.example.otcRecs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt0rH5UhpTlf1Ji2OCC30mKoke58M-q4k',
    appId: '1:639474301712:web:5543dfe79bdd2d4868c395',
    messagingSenderId: '639474301712',
    projectId: 'otc-recs',
    authDomain: 'otc-recs.firebaseapp.com',
    storageBucket: 'otc-recs.firebasestorage.app',
    measurementId: 'G-ENM6H39EGW',
  );
}
